
package com.test.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Function", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Function {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transWords", targetNamespace = "http://webservice/", className = "com.test.service.TransWords")
    @ResponseWrapper(localName = "transWordsResponse", targetNamespace = "http://webservice/", className = "com.test.service.TransWordsResponse")
    @Action(input = "http://webservice/Function/transWordsRequest", output = "http://webservice/Function/transWordsResponse")
    public String transWords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
